name: CI

on: pull_request

jobs:
  tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: php-actions/composer@v1

      - name: Run php-cs-fixer
        run: ./vendor/bin/php-cs-fixer fix --dry-run --diff

      - name: Run phpunit
        run: ./vendor/bin/phpunit tests --colors

      - name: Run psalm
        run: ./vendor/bin/psalm
